### ISSUE TITLE
Idea of a consensus algorithm that utilizes properties of semi-lattice

### ISSUE THREAD

**Issue by iacore** [braid-org/braidjs#26]
I wrote about it here:

https://www.1a-insec.net/blog/70-consensus-pruning-semilattice/

Please peer review this, since I have no idea if it works in practice or not.

**Comment by toomim** [comment]
Here are some reflections on your notes.

> Pruning Semi-lattice

I don't understand the code. Perhaps you'd like to explain it in english?

I'm not sure how you would prune a CRDT semi-lattice directly. Sync9 is able to prune because it constrains all network operations to what we call Observed History (aka [Pure Operational CRDT](https://arxiv.org/pdf/1710.04469)). This is a history format where every operation depends only on the previous version(s) at the time it was created — not on an arbitrarily past operation ID at an arbitrarily past version. I think you'll need this constraint in your history representation in order to prune old history.

I'd be happy to explain the constraint of Observed History that you need, if you'd like.

> Consensus Algorithm
>
> Can we use raft here? Why sync9?

These are different things. First, it would be more appropriate to compare Raft with Antimatter. Sync9 is just a CRDT that uses Observed History/POCRDT. Antimatter is the p2p network algorithm that tells you what history is no longer going to be referenced by future updates from peers, which is closer to Raft/paxos, but still different.

So let's compare Raft/Paxos with Antimatter. Raft and paxos produce consensus on a distributed state machine. That is a lot more than Antimatter. Antimatter just tells you what regions of observed history have been seen by all peers, in the face of network latency, disconnects and reconnects.

Unlike Raft/Paxos, Antimatter+Sync9 do not validate edits, and do not find consensus on state (they don't need to, since they don't implement a notion of edits failing). Raft/Paxos requires a leader election, with two round trips, but Antimatter+Sync9 don't. Sync9 is a CRDT, where you can always apply every edit as soon as you see it, without waiting for round trips. As with any CRDT, validation could be implemented on top, and you could add a consensus algorithm if you want. Also, Raft/Paxos finds consensus on a linear history. CRDTs do not require a linear history. They allow merging. These are different things.

> I have trouble understanding the ack and commit mechanism after reading the [reference implementation](https://github.com/braid-org/braidjs/) over and over. So, I made up my own.

What do you mean by "commit" mechanism? Perhaps you're thinking of the raft/paxos model? This isn't a distributed state machine that commits changes.

For acks, I'd suggest understanding acks via the [three-wave acks](https://braid.org/algorithms/three-wave-acks) post rather than the code, but would like to know where else you're getting stuck so that we can improve that explanation.

> First, every participant keeps track of a list of current peers and the last state received from them.

Is that list of all peers in the network, or only the peers you are immediately connected to? Antimatter works with the latter, which scales much better. It seems like you're broadcasting every peer's state every second? That adds `O(num_peers)` overhead each second, which could get large if e.g. a hacker news audience loads a page.

> Communication happens over unreliable packet exchange network like UDP/IP.

If a new peer joins the network, and that "netjoin" message gets lost, how do the other peers know that they need to wait for this new peer's acks? They could start pruning prematurely, and then break.

> Forgetting about peers unseen after a certain duration
>
> Maybe the [three-wave-ack](https://braid.org/algorithms/three-wave-acks) can be used here?

Just to confirm— this is just for the case where you're marking a peer "dead" after e.g. days or weeks, and giving up on synchronizing with it, right? If so, this is *not* what three-wave acks is for. Three-wave acks is the way to know when a peer that *is* connected has seen a version. It lets you do that without knowing all peers in the network— you only have to keep track of your immediate neighbors in the network. They know their neighbors, and so on, and then transitively the network figures out when everyone has seen a version. This is more efficient than the `O(num_peers)` method you seem to be working on.

> Forgetting saves memory. Will you remember friends you have lost contact with forever? This was a problem in Scuttlebutt, where disk space grows unbounded. [PZP](https://pzp.wiki/guide/intro/) claims to have solved this issue.
>
> When reconnecting after being forgotten, here are some choices:
> 
> 1. Forget about edits since the split.
> 2. Use conventional merge methods on the presentation type. e.g. git merge-file -p current /dev/null other for text. (not relying on the properties of semi-lattice)

With Observed History, you can also ask an "archive" peer for a module of old history that you're missing. This way you can have most peers forget history, but still get it when it's necessary to merge data with an old peer that they've given up on.

**Comment by iacore** [comment]
Thanks for the detailed feedback.

> I don't understand the code. Perhaps you'd like to explain it in english?

... words hard ... I want to formalize it first before explaining it.

> I'd be happy to explain the constraint of Observed History that you need, if you'd like.

Maybe document it on braid.org.

> First, it would be more appropriate to compare Raft with Antimatter.

Sorry, I got the name wrong. We agree about consensus algorithm here.

> Is that list of all peers in the network, or only the peers you are immediately connected to? Antimatter works with the latter, which scales much better. It seems like you're broadcasting every peer's state every second? That adds O(num_peers) overhead each second, which could get large if e.g. a hacker news audience loads a page.

I didn't think about this. Can you document how Antimatter only need to care about connected peers on braid.org?

> If a new peer joins the network, and that "netjoin" message gets lost, how do the other peers know that they need to wait for this new peer's acks? They could start pruning prematurely, and then break.

Use three-wave ack or equivalent for netjoin. The new peer isn't allowed to start editing until all peers have reserved a spot in history graph for it.

> Just to confirm— this is just for the case where you're marking a peer "dead" after e.g. days or weeks, and giving up on synchronizing with it, right? If so, this is not what three-wave acks is for.

See above. It is my idea, not an interpretation of Antimatter+Sync9.

**Comment by toomim** [comment]
> > First, it would be more appropriate to compare Raft with Antimatter.
>
> Sorry, I got the name wrong.  We agree about consensus algorithm here.

Just to be clear, Antimatter is not technically a consensus algorithm. Its purpose is not for nodes to agree on the same data state or value. It is just a way to know when all currently-connected peers have witnessed a particular version of state within the partially-ordered DAG of time.

Paxos/Raft, on the other hand, *are* consensus algorithms.

> Can you document how Antimatter only need to care about connected peers on braid.org?

There are two parts of this. The first part is documented in [three-wave ack](https://braid.org/algorithms/three-wave-acks). You'll notice that this algorithm only cares about connected peers. This algorithm tells you, for the currently connected graph of peers, when all the peers have acknowledged a version, and no peer needs to know all other peers.

The second part is how you deal with connection and disconnection (aka partition) events. This is done with fissure/welcome messages. The basic idea is that whenever a disconnection happens between two nodes, we call that a "fissure", and both sides of the connection broadcast equal and opposite fissure messages throughout their networks. A fissure message tells every peer that receives it that "something disconnected during this ack wave!", and each peer responds by freezing all unacknowledged versions it has in memory (by labeling them with that fissure message) until it receives the opposite side of the fissure, that was broadcast by the peer on the other side of the connection. When it receives the opposite side, it knows that even though one local connection was lost, there is still a connected path through the network to that lost subnet, and thus it can unfreeze all the versions frozen by that fissure, and move on again in synchrony.

A welcome message (what you call a netjoin) thus not only sends the joining peer new operations, but also sends it all the fissures and antifissures that it currently has. Both sides send welcomes, and thus both sides exchange their fissures, and this lets them discover what versions they can unfreeze.

After the network unfreezes versions, some peer will initiate another ack wave, which can acknowledge those unfrozen versions, and once acknowledged, the CRDT (sync9 in this case) knows that it has a new region of history that it can prune, by blooping the operations together into one big operation, obliterating the distinctions between them.

> > If a new peer joins the network, and that "netjoin" message gets lost, how do the other peers know that they need to wait for this new peer's acks? They could start pruning prematurely, and then break.
> 
> Use three-wave ack or equivalent for netjoin. The new peer isn't allowed to start editing until all peers have reserved a spot in history graph for it.

Ah, well then I can point out two potential issues.

First, perhaps I wasn't clear about the issue I'm getting at— I'm concerned about your use of UDP without a way to rebroadcast lost packets. Three-wave ack requires messages between any two peers to rebroadcast when dropped. So if your goal is to do netjoins over UDP without rebroadcasting, then you need rebroadcasting anyway if you want to use three-wave ack, and you might just want to assume reliable connections between peers from the get-go.

Second, the three-wave ack algorithm (along with the fissure/welcome protocol) lets you do this *without* requiring every peer to know every other peer, which scales a lot better, and even lets subnetworks to continue pruning after a partition. You can play with that in the antimatter visualization. Try disconnecting the network into two subnetworks by clicking on an edge in the graph. You'll see that the subnetworks freeze any outstanding versions that weren't acknowledged between them, but all the new versions created within each subnetwork get pruned away.

**Comment by iacore** [comment]
Thanks for the explanation and critique. I understand your algorithm a little better now.

I use the word "consensus algorithm" liberally.

IMHO, the difference between UDP and TCP is too big to assume reliable transmission from the get go. I'm now thinking about how networked fighting games reach visual consistency fast with various techniques. Maybe this is one giant problem which I don't know where CRDT sit in it. Being fast is not a hard constraint for text editing, yet when I want to apply the technique to games, the states need to converge fast.
